"""Shared constants for ProcureWatch UK."""

GOVERNMENT_ERAS = {
    "May": {"start": "2017-01-01", "end": "2019-07-23", "color": "#4A6FA5"},
    "Johnson": {"start": "2019-07-24", "end": "2022-09-05", "color": "#2E5E4E"},
    "Truss": {"start": "2022-09-06", "end": "2022-10-24", "color": "#8B4513"},
    "Sunak": {"start": "2022-10-25", "end": "2024-07-04", "color": "#5C4B7A"},
    "Starmer": {"start": "2024-07-05", "end": "2026-12-31", "color": "#C41E3A"},
}

DEPARTMENTS = [
    "Cabinet Office",
    "Department for Business and Trade",
    "Department for Education",
    "Department for Energy Security and Net Zero",
    "Department for Environment, Food and Rural Affairs",
    "Department for Science, Innovation and Technology",
    "Department for Transport",
    "Department for Work and Pensions",
    "Department of Health and Social Care",
    "Foreign, Commonwealth & Development Office",
    "HM Revenue & Customs",
    "HM Treasury",
    "Home Office",
    "Ministry of Defence",
    "Ministry of Justice",
    "NHS England",
    "NHS Scotland",
    "Birmingham City Council",
    "Greater Manchester Combined Authority",
    "Leeds City Council",
    "London Borough of Camden",
    "Transport for London",
    "Westminster City Council",
]

DEPARTMENT_TAGS = {
    "Cabinet Office": "Central Govt",
    "Department for Business and Trade": "Central Govt",
    "Department for Education": "Central Govt",
    "Department for Energy Security and Net Zero": "Central Govt",
    "Department for Environment, Food and Rural Affairs": "Central Govt",
    "Department for Science, Innovation and Technology": "Central Govt",
    "Department for Transport": "Central Govt",
    "Department for Work and Pensions": "Central Govt",
    "Department of Health and Social Care": "Central Govt",
    "Foreign, Commonwealth & Development Office": "Central Govt",
    "HM Revenue & Customs": "Central Govt",
    "HM Treasury": "Central Govt",
    "Home Office": "Central Govt",
    "Ministry of Defence": "Central Govt",
    "Ministry of Justice": "Central Govt",
    "NHS England": "NHS",
    "NHS Scotland": "NHS",
    "Birmingham City Council": "Local Authority",
    "Greater Manchester Combined Authority": "Local Authority",
    "Leeds City Council": "Local Authority",
    "London Borough of Camden": "Local Authority",
    "Transport for London": "Local Authority",
    "Westminster City Council": "Local Authority",
}

CPV_CATEGORIES = {
    "45000000": "Construction work",
    "48000000": "Software and IT systems",
    "71000000": "Architectural and engineering services",
    "72000000": "IT services",
    "73000000": "Research and development",
    "75000000": "Public administration services",
    "76000000": "Environmental services",
    "79000000": "Business and management consultancy",
    "79100000": "Legal services",
    "79110000": "Legal advisory services",
    "79140000": "Legal advisory and representation",
    "80000000": "Education and training",
    "85000000": "Health and social work",
    "90000000": "Sewage, refuse and cleaning",
    "92000000": "Recreational, cultural and sporting",
}

CONSULTANCY_SUPPLIERS = [
    "Deloitte LLP",
    "PwC LLP",
    "KPMG LLP",
    "Ernst & Young LLP",
    "McKinsey & Company",
    "Boston Consulting Group",
    "Accenture UK Limited",
    "PA Consulting Group",
    "Capgemini UK plc",
    "IBM United Kingdom Limited",
    "Atos IT Services UK Ltd",
    "CGI IT UK Limited",
    "Serco Group plc",
    "Capita plc",
    "Kainos Software Limited",
]

LAW_FIRMS = [
    "Freshfields Bruckhaus Deringer LLP",
    "Linklaters LLP",
    "Clifford Chance LLP",
    "Allen & Overy LLP",
    "Herbert Smith Freehills LLP",
    "Pinsent Masons LLP",
    "DLA Piper UK LLP",
    "Eversheds Sutherland LLP",
    "CMS Cameron McKenna Nabarro Olswang LLP",
    "Browne Jacobson LLP",
    "Government Legal Department",
    "Bindmans LLP",
    "Leigh Day",
    "Bindmans LLP",
]

GENERAL_SUPPLIERS = [
    "BAE Systems plc",
    "Rolls-Royce plc",
    "Siemens plc",
    "Carillion plc (legacy)",
    "Balfour Beatty plc",
    "Kier Group plc",
    "Mitie Group plc",
    "G4S Limited",
    "Sodexo UK Limited",
    "BT Group plc",
    "Vodafone UK",
    "Amazon Web Services EMEA SARL",
    "Microsoft Limited",
    "Oracle Corporation UK Limited",
    "Palantir Technologies UK Ltd",
    "Thales UK Limited",
    "Leonardo UK Ltd",
    "Fujitsu Services Limited",
    "Northrop Grumman UK Ltd",
    "Raytheon UK Limited",
]

LEGAL_KEYWORDS = [
    "legal advice",
    "solicitors",
    "judicial review",
    "litigation",
    "barrister",
    "counsel",
    "legal services",
    "law firm",
    "legal representation",
    "dispute resolution",
    "arbitration",
    "tribunal",
]

CONSULTANCY_KEYWORDS = [
    "consultancy",
    "consulting",
    "advisory",
    "strategy review",
    "transformation programme",
    "business case",
    "feasibility study",
    "implementation partner",
    "professional services",
]

RED_FLAG_DEFINITIONS = {
    "duplicate_risk": {
        "label": "Duplicate Risk",
        "description": "Very similar contract title/description awarded to the same supplier within the last 24 months.",
        "weight": 35,
    },
    "repeated_consultancy": {
        "label": "Repeated Consultancy",
        "description": "Same department awarding multiple consultancy-style contracts in similar categories within 18 months.",
        "weight": 30,
    },
    "value_spike": {
        "label": "Value Spike",
        "description": "Contract value exceeds 3× the median for similar contracts in the same category and department (recent years).",
        "weight": 35,
    },
}

NOTABLE_PROJECTS = [
    {
        "name": "HS2 — Bat Tunnel Mitigation",
        "department": "Department for Transport",
        "original_cost_m": 35000,
        "final_cost_m": 42000,
        "status": "Ongoing delays",
        "explanation": "Environmental mitigation including bat tunnels and ecological surveys added significant costs and timetable delays to Phase 1.",
    },
    {
        "name": "HS2 — Euston Station Redesign",
        "department": "Department for Transport",
        "original_cost_m": 2800,
        "final_cost_m": 4700,
        "status": "Scope revised",
        "explanation": "Repeated redesigns and scope changes at Euston have driven cost escalation beyond original estimates.",
    },
    {
        "name": "NHS National Programme for IT (NPfIT)",
        "department": "Department of Health and Social Care",
        "original_cost_m": 2300,
        "final_cost_m": 12000,
        "status": "Cancelled (2011)",
        "explanation": "Landmark IT programme widely cited as one of the largest public sector IT failures; costs ballooned before cancellation.",
    },
    {
        "name": "Royal Navy Fleet Solid Support Ships",
        "department": "Ministry of Defence",
        "original_cost_m": 1500,
        "final_cost_m": 2100,
        "status": "Delayed procurement",
        "explanation": "Repeated tender delays and industrial strategy disputes extended timelines and increased unit costs.",
    },
    {
        "name": "Garden Bridge (London)",
        "department": "Transport for London",
        "original_cost_m": 60,
        "final_cost_m": 53,
        "status": "Cancelled (2017)",
        "explanation": "Project cancelled after £53m spent on design and consultancy without construction commencing.",
    },
    {
        "name": "Smart Motorways Programme",
        "department": "Department for Transport",
        "original_cost_m": 6000,
        "final_cost_m": 9000,
        "status": "Paused / reviewed",
        "explanation": "Safety reviews and retrofitting requirements increased total programme costs beyond initial business case.",
    },
]

DATA_SOURCES = {
    "contracts_finder": "https://www.contractsfinder.service.gov.uk/",
    "ocds_bulk": "https://data.open-contracting.org/en/publication/143",
    "ocds_api": "https://www.contractsfinder.service.gov.uk/api/rest/get",
}

REQUIRED_COLUMNS = [
    "ocid",
    "notice_id",
    "title",
    "buyer",
    "supplier",
    "award_date",
    "value_gbp",
    "cpv_code",
    "category",
    "description",
]